### ISSUE TITLE
Contracts with similar ABIs are meshed together in report

### ISSUE THREAD

**Issue by sebastiantf** [cgewecke/hardhat-gas-reporter#154]
I have two contracts `Campaigns`, `CampaignsNativeGaslessClaim` which have almost similar ABIs. The gas report only have separate functions which have different ABIs. The counts for the functions with same ABIs seem to suggest that they're being meshed together instead of staying separate.

I have confirmed that all methods are being called on both contracts. Particularly the following methods are not reported for `CampaignsNativeGaslessClaim`:
- `claim`
- `setClaimFee`
- `setTrustedAddress`
- `withdrawCampaign`
- `withdrawTotalClaimFees`

`createCampaign` has different ABIs on both contracts, so that seem to be reported separately correctly

<img width="1073" alt="Screenshot 2023-07-03 at 4 42 14 PM" src="https://github.com/cgewecke/hardhat-gas-reporter/assets/36922376/a9c74d7e-2004-4832-9a7d-8789f9d8bcce">

**Comment by cgewecke** [comment]
Apologies for the very late response here - do you remember if this problem was in the context of using OZ's upgradeable contracts? (Have tentatively labeled it that way)

**Comment by sebastiantf** [comment]
Yes. I was using OZ's upgradeable contract

**Comment by CWhits** [comment]
Similar experience. I am testing two smart contracts, one a regular ERC721 and another one that is OZ's upgradeable. They are almost identical and the contract name displayed is just the regular ERC721 although every test is being completed.

**Comment by cgewecke** [comment]
@CWhits Yes, when a proxy sits in front of a target contract the gas-reporter has to fall back on function selectors alone to figure out what's being called. If there are method name collisions the contract attributions can be incorrect. 

In the original version of this plugin (eth-gas-reporter) [there was an option to help the reporter navigate proxies][1] but no one used it AFAIK.

Am going to add explicit support for OZ upgradeable in [the next major version][2] since it's become much more of an issue. Working on this this month however it will probably not be published in beta before March. 

[1]: https://github.com/cgewecke/eth-gas-reporter/blob/master/docs/advanced.md#resolving-method-identities-when-using-proxy-contracts
[2]: https://github.com/cgewecke/hardhat-gas-reporter/issues/158

**Comment by cgewecke** [comment]
This has been fixed in the latest version (2.0). If you're using OZ's upgrades plugin the reporter will automatically resolve proxied contracts. 

Closing but just ping if you continue to have problems with this.
