### ISSUE TITLE
Issues with switch to typescript

### ISSUE THREAD

**Issue by YannyD** [cgewecke/hardhat-gas-reporter#56]
I can't get any methods to show up when I switch the test files to typescript. I have:
1.) Added hardhat.config.ts to "include" in tsconfig.json
2.) passed (args, hre) into the describe fallback function
3.) Use import instead of require

My tests all pass, but the tool doesn't show any methods or gas stats. When I convert the exact same test to javascript, the gas stats do appear. What else should we look out for?

I am on ubuntu 20.04

**Comment by cgewecke** [comment]
Hi. It's hard to tell without seeing your repo. 

A simple working TS example can be seen at [sushiswap/hardhat-foundation][1].
```
$ git clone https://github.com/sushiswap/hardhat-foundation.git
$ yarn
$ npm run test:gas
```

**Output:**

![Screen Shot 2021-02-05 at 10 08 12 AM](https://user-images.githubusercontent.com/7332026/107071607-d1a76d80-6799-11eb-9243-9fc83d74a488.png)



[1]: https://github.com/sushiswap/hardhat-foundation

**Comment by cgewecke** [comment]
Closing, not enough info here to debug and the plugin seems to work w/ TS based on the example above.

Please just ping if you want to pursue this and I will re-open.

**Comment by YannyD** [comment]
Here is the repo if you can still take a look:

https://github.com/YannyD/PandiFiPrototypeWithHardhat/tree/master

**Comment by cgewecke** [comment]
@YannyD 

I think waffle's not being pulled into the project correctly - see [the relevant plugin docs][1].

Instead of importing directly from `ethereum-waffle`, you have to import `waffle` from `hardhat` and use its methods. This ensures that the tests run on the hardhat network instead of a ganache-core provider (which the reporter can't connect to). 

The gasReporter option `enabled` should be set true (instead of false) and `url` should be deleted. 

[1]: https://hardhat.org/plugins/nomiclabs-hardhat-waffle.html#environment-extensions

**Comment by YannyD** [comment]
Ya that makes sense.  Everything is working now.  Great plugin.  Thanks so much!
