### ISSUE TITLE
Avoid results being subject to ETH price fluctuations

### ISSUE THREAD

**Issue by willisk** [cgewecke/hardhat-gas-reporter#82]
Is there a way to just input a fixed value for gas fiat price estimation?

I like looking at $ values, since they are easier for me to process. When optimising functions it's hard to tell whether a change was good or bad, since I tend to look at the dollar values, but then I have to figure out whether it might've just been a jump in the eth/usd price.

Why not have the option to just input a fixed price for reference (say 4k$ eth, for example)? This would remove the need for registering with an api and would allow for a better reference for testing.

Or even better: show the prices in eth cost, instead of some currency. I currently don't see an option for this.

**Comment by aspiers** [comment]
Nice idea, but perhaps rename the issue title "Avoid results being subject to ETH price fluctuations" so that it's clearer what you want.  To check my understanding, you are proposing at least one of the two new features:

1. feature to fix ETH price so that fiat prices can be displayed without fluctuations over time
2. showing prices in ETH, skipping currency

**Comment by willisk** [comment]
Exactly. And yes, that title does bring it to the point

**Comment by concave-dash** [comment]
Agree on this. Price in ETH are much more convenient to get the difference.

**Comment by cgewecke** [comment]
In the latest version you can do this by setting the tokenPrice option as below:
```
tokenPrice: "1"
```

https://github.com/cgewecke/hardhat-gas-reporter/releases/tag/v2.0.0
