### ISSUE TITLE
Nonsensical Output When Running Tests

### ISSUE THREAD

**Issue by DanielGelfand** [cgewecke/hardhat-gas-reporter#83]
When I run my tests with the gas reporter (npx hardhat test), my tests output random characters such as ͇͇͎tͬ͑ͩ and the tests never end.

I am running hardhat on a Windows machine. Has this problem ever been encountered before?

Node version: v12.18.4
Hardhat Gas reporter: v1.0.6

**Comment by cgewecke** [comment]
@DanielGelfand  

I think it might be the same issue as [hardhat 2235][1] which has been traced to a bug in one of `colors.js`'s dependencies ([introduced today ~5 hours ago][2])

A workaround suggested in the Hardhat issue is to use yarn's resolutions feature to pin `colors` to v1.4.0 in your project's package.json like this:
```
"resolutions": {
    "**/colors": "1.4.0"
  }
```
... and install using yarn.

Does that resolve it on your end?
   
[1]: https://github.com/nomiclabs/hardhat/issues/2235#issue-1097309945
[2]: https://github.com/Marak/colors.js/issues/289

**Comment by cgewecke** [comment]
Looked into this a bit ... will patch at eth-gas-reporter since there seems to be some kind controversy swirling around the package atm.

+ https://github.com/Marak/colors.js/commit/074a0f8ed0c31c35d13d28632bd8a049ff136fb6#r63165690
+ http://web.archive.org/web/20210704022108/https://github.com/Marak/faker.js/issues/1046
